### ISSUE TITLE
What have you learned making Babel?

### ISSUE THREAD

**Issue by arthurvr** [sebmck/ama#1]

**Comment by sebmck** [comment]
Oh boy, where do I start. Babel has always been a learning project for me, and it still is. It's basically my testbed for experimentation of things I want to try out which I guess is why it's always moved pretty quickly. Back at the end of September last year I realised that there was a massive gap in my understanding of core Computer Science concepts. From there I started 6to5, where I slowly learnt about ASTs, parsers, compilers etc and it's now manifested into what Babel is today.

Another big one would have to be community management. Just learning how to cope with pessimism, nasty users and general issue triage is extremely difficult. What can start out as an extremely simple task can quickly become overwhelming and extremely draining. Working out how to balance that and not let people get to my head so much is still an ongoing battle.

**Comment by kentcdodds** [comment]
From what I've seen of tweets from @arthurvr and @sindresorhus, they totally get you there. I haven't been trolled quite like they have, but I get you too. Entitlement is a real thing that kills motivation. Keep going man! Most of us appreciate it! I wouldn't be writing ES6 if it weren't for you! :-)
