### ISSUE TITLE
How many languages do you speak?

### ISSUE THREAD

**Issue by julen** [sebmck/ama#12]
Or any plans to learn any new (non-programming) language?

**Comment by sebmck** [comment]
I learnt Japanese all through school although I'm not very fluent. Before that I learnt Italian for a couple years in primary school although my knowledge of Italian has been fused with the little Spanish I've picked up from watching Dora the Explorer so attempting to count to 10 in Italian is interesting. No current plans to learn a new language but if I had to pick I'd likely "finish" learning Japanese.
