### ISSUE TITLE
What is a skill you'd like to learn and why?

### ISSUE THREAD

**Issue by sindresorhus** [sebmck/ama#14]

**Comment by sebmck** [comment]
Probably the more lower level workings of a computer. I'm having a similar problem now to what I had when I started Babel in that there's soooo much that I don't know and I really want to learn it. I'll probably mess around with writing my own hobby OS to understand more about how computers and operating systems work.

**Comment by sebmck** [comment]
I kinda cheated with picking something computer/programming related. Another one would probably be learning how to cook, I did hospitality in high school to have a fall back in case this programming thing didn't work out and realised that it's actually a lot of fun. I'm pretty crap at it but becoming confident enough to make my own food (especially honey chicken omfg, see #9) would be awesome.

**Comment by drewvolz** [comment]
@sebmck I hear [this guide](https://github.com/SamyPesse/How-to-Make-a-Computer-Operating-System) is decent at understanding the fundementals from scratch.
