### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [sebmck/ama#16]
Editor, terminal, tools, themes, fonts, process, etc.

**Comment by sebmck** [comment]
I use iTerm 2 for my console with a custom `.bash_profile`:

<img width="836" alt="screen shot 2015-07-14 at 1 38 15 pm" src="https://cloud.githubusercontent.com/assets/853712/8673348/a15b47fa-2a2d-11e5-8695-458e4b63cc99.png">

For my editor I use Sublime Text 2 with the [Oceanic Next color scheme](https://github.com/voronianski/oceanic-next-color-scheme) and the [babel-sublime syntax definition](https://github.com/babel/babel-sublime):

<img width="1210" alt="screen shot 2015-07-14 at 1 39 47 pm" src="https://cloud.githubusercontent.com/assets/853712/8673362/cebaddfa-2a2d-11e5-95e4-af0eb7d90d5b.png">

I also use good ol' fashion `git gui` to make stage files and make commits:

<img width="1386" alt="screen shot 2015-07-14 at 1 40 24 pm" src="https://cloud.githubusercontent.com/assets/853712/8673375/e67d70b0-2a2d-11e5-8bf2-365808335e85.png">
