### ISSUE TITLE
What's your favorite gif?

### ISSUE THREAD

**Issue by sindresorhus** [sebmck/ama#18]

**Comment by sebmck** [comment]
Definently

![wiggle](https://cloud.githubusercontent.com/assets/853712/8673176/5217af2c-2a2c-11e5-949a-c8eec09762ba.gif)

Courtesy of @marcysutton.

**Comment by marcysutton** [comment]
Ha! Love it!

**Comment by sebmck** [comment]
Updating with some of my latest favourites...

![ttijeaj](https://cloud.githubusercontent.com/assets/853712/9265172/6939952c-4227-11e5-83a5-648743ddfb27.gif)

![giphy](https://cloud.githubusercontent.com/assets/853712/9265175/72a40426-4227-11e5-84c6-9822564686ab.gif)
