### ISSUE TITLE
Has anyone ever read the Babel contributing.md?

### ISSUE THREAD

**Issue by sindresorhus** [sebmck/ama#19]
https://github.com/babel/babel/blob/master/CONTRIBUTING.md

**Comment by sebmck** [comment]
People don't even [read README.md](https://github.com/babel/babel/issues?q=is%3Aissue+see+the+readme+is%3Aclosed) so reading `CONTRIBUTING.md` is probably waaay too much of a stretch, I wish GitHub had a better way to encourage users not make these kinds of issues.

**Comment by jmeas** [comment]
lol
