### ISSUE TITLE
What other programming languages you know?

### ISSUE THREAD

**Issue by drKraken** [sebmck/ama#2]

**Comment by sebmck** [comment]
I actually started off with PHP. When I was 14 my school introduced a website filter which means I couldn't go onto any websites to play flash games. I then setup a PHProxy script and then monkey patched it into some off the shelf user management system. After that I dabbled a bit in Ruby, Python and Perl before settling on JavaScript. I really want to branch out and learn more about other more "exotic" programming languages like Smalltalk and Clojure. I'm also planning on dabbling in more lower level languages like Rust/C etc.
