### ISSUE TITLE
If I were to travel to Australia for the first time, where should I go and why?

### ISSUE THREAD

**Issue by sindresorhus** [sebmck/ama#22]

**Comment by sebmck** [comment]
There's not really a whole lot in terms of historical buildings which is really disappointing as I've only just realised that they're very common in areas like Europe. The stuff that immediately comes to mind is Harbor Bridge and the Opera House in Sydney which is probably the most iconic Australian landmarks:

![sydney harbor and opera house](https://upload.wikimedia.org/wikipedia/commons/9/91/Sydney_opera_house_2010.jpg)

Australia also has a ton of awesome beaches such as Bondi Beach in Sydney:

![bondi beach](http://i1.trekearth.com/photos/9305/bondi_beach_after_city_to_surf.jpg)

I also hear that Uluru is pretty awesome although I've never been:

![uluru](http://www.ulurudaytours.com.au/uploads/slideshow/slideshow-1/ayers_rock_day_tours.jpg)

There's also a lot of variety in Australia, there's snow mountains (which are very close to my hometown) which surprises a lot of people although it's likely not very exciting if you come from a snowy/cold country:

![mt buller](http://www.arlberg.com.au/images/slideshow_images/home1.jpg)

There's also lots of historical towns such Glenrowan (which is again, very close to my hometown):

![glenrowan](http://www.nedkellytouringroute.com.au/media/7273/glenrowanbigned_r.jpg)

Glenrowan was the location of a battle between some bush rangers and law enforcement officers. Basically some criminals made some armour out of stolen farm equipment and went around doing criminal stuff. There's some cool sites there to see.

There's probably a whole lot more but my memory is failing on me right now. When I started writing this I didn't think there was much really but there's actually a ton.

**Comment by melvin0008** [comment]
The snow mountains look amazing!
