### ISSUE TITLE
If you were lucky enough to win the lottery, what would you do with the money?

### ISSUE THREAD

**Issue by sindresorhus** [sebmck/ama#25]

**Comment by sebmck** [comment]
Depends on how much but I'd do love to do the following things (ordered by preference):

1. Buy a house and car for my Mum and pay off my parents debt.
2. Save enough so I don't have to worry about money for the rest of my life.
3. Donate to a charity.

**Comment by jmeas** [comment]
> Buy a house and car for my Mum and pay off my parents debt.

awwww
