### ISSUE TITLE
What are your programming books / resources for Javascript?

### ISSUE THREAD

**Issue by deezahyn** [sebmck/ama#28]

**Comment by sebmck** [comment]
[MDN](https://developer.mozilla.org/en-US/) would have to be a good one. I've never really learnt/gone to a single resource. I've usually just googled for questions and used random sites, reading code and understanding it works has been another big one. These days I just go straight to the specifications to learn how APIs etc work. I also used [w3schools](http://www.w3schools.com/) very early when I was learning, it gets a lot of flack (rightfully so) but it's been invaluable.
