### ISSUE TITLE
How do you find the time and means to work on Babel?

### ISSUE THREAD

**Issue by 0x8890** [sebmck/ama#3]
Employers typically don't care for free software even if they reap the benefits of it, and there are a lot of programmers who would rather be working on free software but are instead employed working on proprietary business applications.

**Comment by sebmck** [comment]
I sacrifice a lot of my personal and social time to work on Babel. You can likely tell by my [contribution graph](https://github.com/sebmck) the times where I've either been very busy with work/social stuff and when I've had large amounts of free time to do sprints. Mostly I either sneak in commits during work hours or work on it during the evening or weekends.

I'm also **extremely** fortunate to have now landed a job recently where I'll get to work largely on OSS, this means that I'll hopefully be able to shift my personal time into my work time which frees me up to spend my free time working on other projects and hobbies.  :blush:
