### ISSUE TITLE
Are you 18 for reals?!

### ISSUE THREAD

**Issue by srph** [sebmck/ama#32]

**Comment by sebmck** [comment]
Yes. Who cares? Making a big deal about someones age is stupid and makes people feel like shit. I've [tweeted](https://twitter.com/sebmck/status/620381205112975361) about this before and it just reinforces my view that there's a very strong sense of ageism in tech.

**Comment by srph** [comment]
No, I'm 18, and I'm just so amazed.

**Comment by backspaces** [comment]
I'm 73 and feel exactly the same!
