### ISSUE TITLE
What are you going to be doing at Facebook?

### ISSUE THREAD

**Issue by kentcdodds** [sebmck/ama#4]
https://twitter.com/kentcdodds/status/620770749926617089

Congratulations 🎉

**Comment by sebmck** [comment]
Thanks! I'll be working on product infrastructure, mostly on Babel. Hopefully that's not the only thing I'll be working on as I'm super excited to be able to branch out and expand into other areas.

**Comment by kentcdodds** [comment]
Great to hear. I know occasionally I'll work on open source during work and I can justify it by the fact that we use the tool at work, but I still feel a little guilty. Nice that your job description includes open source. Also cool that you'll be able to branch out and continue learning and growing :+1:
