### ISSUE TITLE
What is it like to move to London?

### ISSUE THREAD

**Issue by gaearon** [sebmck/ama#40]
Now that you have moved, what are your impressions?
What surprised you?
Do you have a favorite place to go out yet?
Do you meet people outside work?

**Comment by sebmck** [comment]
> Now that you have moved, what are your impressions?

I always saw London as a pitstop until I could apply for an O1 or some miracle happened and I could get into the promiseland that is the United States. After spending some time in the bay area (the only place where I'd realistically move to) I've decided that it's not really for me. There's so much dumb drama and if you work for a big tech company that's outside of the direct city then the commute is painful and you really have to sacrifice a lot.

London is super easy. I can literally walk out the front doors of the office and be in the city and do whatever. Rent is pricey but I'm compensated pretty well so can afford to get a place that's a short walk from the office which is really nice. The UK is more like Australia than the US too which is nice and there's a lot of Australians here which _sorta_ helps with homesickness.

> What surprised you?

When I was working at CloudFlare I actually made a page on the internal wiki of things that surprised me.

> ### Guide for Australians
> 
> Under the extremely slim chance that another Australian joins the London office here are some things that have blown my (Sebastian McKenzie) mind:
> 
> - KFC is putrid, don't eat it
> - Fanta is yellow, not orange
> - Whenever you get pizza they give you dipping sauce (wtf?)
> - Meatlovers pizza has meatballs on it (again wtf?)
> - They don't sell double quarter pounders at McDonalds here
> - McDonalds is very select on their "meals". You can't get a double cheeseburger meal for example
> - The 2L bottles are tall and skinny rather than short and stout
> - Wog means something different here (hint: don't use it)
> - When you use a debit card you don't have to select your account type
> - Creaming soda here isn't the red drink from Kirks
> - Cheese here costs WAY too much
> - If you got your impression of British people from Oliver Twist and Clockwork Orange then you're in for a shock (hint: they're worse)
> - Birds are boring
> - Double decker buses get old, fast
> - The Jeremy Kyle show is an amazing confidence booster
> - ...TO BE CONTINUED...

> Do you have a favorite place to go out yet?

Not yet!

> Do you meet people outside work?

Not as many as I'd like. I didn't really put much thought into making friends before I moved here but it's **much** harder than I would've thought. I'm also fairly shy around people I don't know fairly well which makes it even more difficult.

**Comment by gaearon** [comment]
Awesome answers, thanks! :+1: 

>After spending some time in the bay area (the only place where I'd realistically move to) I've decided that it's not really for me. There's so much dumb drama and if you work for a big tech company that's outside of the direct city then the commute is painful and you really have to sacrifice a lot.

I haven't been to London yet (lol what am I doing), but assuming it's at least somewhat similar to Europe (e.g. Berlin), this is what I feel about London vs Bay Area too. Especially considering I don't drive.

**Comment by sebmck** [comment]
I hadn't even left Australia before I decided to move to London so I was in the same boat as you. :stuck_out_tongue: There's a lot variety in terms of everything that I don't think you'd have an issue finding parts that you'd at least enjoy if not most of it.
