### ISSUE TITLE
Selfie

### ISSUE THREAD

**Issue by kentcdodds** [sebmck/ama#5]
To continue with the tradition: sindresorhus/ama#75, passy/ama#28, stephenplusplus/ama#19 kentcdodds/ama#4

**Comment by sebmck** [comment]
> Let the force be with you

 - Gandalf

![img_0904](https://cloud.githubusercontent.com/assets/853712/8679657/e38e43b8-2a53-11e5-9fa6-f079a46f3de7.JPG)

**Comment by moimikey** [comment]
Yaaaasssss

**Comment by JuanitoFatas** [comment]
`transform: rotate(90deg);`

**Comment by sebmck** [comment]
If you take landscape selfies then u can't be my friend
