### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by kentcdodds** [sebmck/ama#6]
As @sindresorhus [says](https://github.com/kentcdodds/ama/issues/5), it tells a lot about a person :-)

**Comment by sebmck** [comment]
![img_0873](https://cloud.githubusercontent.com/assets/853712/8671996/bddf1f52-2a21-11e5-96e5-dbd24802258c.PNG)

which isn't much fun, so here's my second screen:

![img_0874](https://cloud.githubusercontent.com/assets/853712/8671998/c775f086-2a21-11e5-9a36-530a475724ae.PNG)

**Comment by kentcdodds** [comment]
Curious, who's that in your background?

**Comment by sebmck** [comment]
My little brother. :blush: It was the last photo I took before I left Australia to move to London.

**Comment by yangli1990** [comment]
Nice, does Tinder work?

**Comment by sebmck** [comment]
[yes](https://twitter.com/samccone/status/642193885997895680) cc @samccone

**Comment by samccone** [comment]
![29fee5t](https://cloud.githubusercontent.com/assets/883126/9856106/9b4a1dd0-5ac7-11e5-8b9a-4651e523bf91.jpg)
