### ISSUE TITLE
What did you have for dinner last night?

### ISSUE THREAD

**Issue by HelloImA** [sebmck/ama#7]

**Comment by sebmck** [comment]
Five Guys! Bacon cheeseburger with BBQ sauce, a small fries and a drink. :hamburger: :fries:

**Comment by gaearon** [comment]
Five Guys are *good*. Does anybody in Europe make burgers like theirs?

**Comment by sebmck** [comment]
@gaearon Five Guys are in the UK!

**Comment by sebmck** [comment]
There's 10 in London alone. List of stores [here](https://www.fiveguys.co.uk/findstore).

**Comment by gaearon** [comment]
>@gaearon Five Guys are in the UK!

![tumblr_inline_nv90gtlfpv1t4tu37_500](https://cloud.githubusercontent.com/assets/810438/10286941/1a620150-6b99-11e5-8fef-d17c6090f0af.gif)
